<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class DailyFinancialReport extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'report_date',
        'total_revenue',
        'total_expenses',
        'net_profit',
        'cash_balance',
        'bank_balance',
        'mobile_wallet_balance',
        'total_assets',
        'total_liabilities',
        'equity',
        'transactions_count',
        'is_auto_generated',
        'report_data',
        'generated_by',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'report_date' => 'date:Y-m-d', // Fixed timezone offset
        'total_revenue' => 'decimal:2',
        'total_expenses' => 'decimal:2',
        'net_profit' => 'decimal:2',
        'cash_balance' => 'decimal:2',
        'bank_balance' => 'decimal:2',
        'mobile_wallet_balance' => 'decimal:2',
        'total_assets' => 'decimal:2',
        'total_liabilities' => 'decimal:2',
        'equity' => 'decimal:2',
        'transactions_count' => 'integer',
        'is_auto_generated' => 'boolean',
        'report_data' => 'array',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
    ];

    /**
     * Get the user who generated this report.
     */
    public function generatedBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'generated_by');
    }

    /**
     * Scope to filter by date range.
     */
    public function scopeDateRange($query, $startDate, $endDate)
    {
        return $query->whereBetween('report_date', [$startDate, $endDate]);
    }

    /**
     * Scope to get auto-generated reports only.
     */
    public function scopeAutoGenerated($query)
    {
        return $query->where('is_auto_generated', true);
    }

    /**
     * Scope to get manually generated reports only.
     */
    public function scopeManuallyGenerated($query)
    {
        return $query->where('is_auto_generated', false);
    }

    /**
     * Check if report is profitable.
     */
    public function isProfitable(): bool
    {
        return $this->net_profit > 0;
    }

    /**
     * Get profit margin percentage.
     */
    public function getProfitMarginAttribute(): float
    {
        if ($this->total_revenue > 0) {
            return ($this->net_profit / $this->total_revenue) * 100;
        }
        return 0;
    }

    /**
     * Get formatted revenue.
     */
    public function getFormattedRevenueAttribute(): string
    {
        return number_format($this->total_revenue, 2);
    }

    /**
     * Get formatted expenses.
     */
    public function getFormattedExpensesAttribute(): string
    {
        return number_format($this->total_expenses, 2);
    }

    /**
     * Get formatted net profit.
     */
    public function getFormattedNetProfitAttribute(): string
    {
        return number_format($this->net_profit, 2);
    }
}
