<?php

namespace App\Modules\Admin\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Modules\Website\Models\WebsiteOrder;
use App\Modules\Website\Services\PaymentLinkService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;

class AdminPaymentLinkController extends Controller
{
    /**
     * Generate a payment link for an order
     * POST /api/v2/admin/orders/{id}/generate-payment-link
     *
     * NOTE: Payment links use EPS gateway only
     * - Supports full and partial payments
     * - 7-day expiration
     * - 32-character unique token
     * - Direct redirect to EPS payment gateway
     */
    public function generate(Request $request, $orderId)
    {
        try {
            // Find order
            $order = WebsiteOrder::find($orderId);
            if (!$order) {
                return response()->json([
                    'status' => false,
                    'error' => 'Order not found'
                ], 404);
            }

            // Validate custom amount (if provided)
            $customAmount = $request->input('amount');
            if ($customAmount !== null) {
                $customAmount = (float)$customAmount;

                // Validate amount
                if ($customAmount <= 0) {
                    return response()->json([
                        'status' => false,
                        'error' => 'Payment amount must be greater than 0'
                    ], 422);
                }

                if ($customAmount > $order->total_amount) {
                    return response()->json([
                        'status' => false,
                        'error' => 'Payment amount cannot exceed order total (' . $order->total_amount . ' BDT)'
                    ], 422);
                }
            }

            // Generate payment link
            $linkData = PaymentLinkService::generatePaymentLink($order, $customAmount);

            Log::info('Payment link generated by admin', [
                'order_id' => $orderId,
                'admin_id' => auth()->id(),
                'amount' => $linkData['amount'],
                'token' => $linkData['token']
            ]);

            return response()->json([
                'status' => true,
                'data' => [
                    'token' => $linkData['token'],
                    'url' => $linkData['url'],
                    'expires_at' => $linkData['expires_at'],
                    'amount' => $linkData['amount'],
                    'order_total' => $order->total_amount,
                ]
            ]);

        } catch (\Exception $e) {
            Log::error('Failed to generate payment link', [
                'order_id' => $orderId,
                'error' => $e->getMessage()
            ]);

            return response()->json([
                'status' => false,
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Get all payment links for an order
     * GET /api/v2/admin/orders/{id}/payment-links
     */
    public function getOrderLinks($orderId)
    {
        try {
            // Find order
            $order = WebsiteOrder::find($orderId);
            if (!$order) {
                return response()->json([
                    'status' => false,
                    'error' => 'Order not found'
                ], 404);
            }

            // Get payment links
            $links = PaymentLinkService::getOrderPaymentLinks($order);

            return response()->json([
                'status' => true,
                'data' => $links->map(function ($link) {
                    return [
                        'token' => $link->payment_link_token,
                        'amount' => $link->link_amount,
                        'status' => $link->status,
                        'created_at' => $link->created_at,
                        'expires_at' => $link->link_expires_at,
                        'used_at' => $link->paid_at,
                        'is_expired' => $link->link_expires_at && $link->link_expires_at->isPast(),
                    ];
                })->values()
            ]);

        } catch (\Exception $e) {
            Log::error('Failed to get payment links', [
                'order_id' => $orderId,
                'error' => $e->getMessage()
            ]);

            return response()->json([
                'status' => false,
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
